# Generated by Django 5.1.2 on 2024-10-31 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customuser_alter_salesreport_salesperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='salesperson',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='SalesReport',
        ),
    ]
